<a href="https://colab.research.google.com/github/Anirudhsatheesh/AI/blob/main/Machine%20learning/Ensemble_Techniques(XGboost%2CRandom_Forest%2CAdaboost%2CCatboost).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install catboost

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 MB 8.9 MB/s eta 0:00:00


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import catboost as cb
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import AdaBoostRegressor
from xgboost import XGBRegressor

In [3]:
df= pd.read_csv('/content/sample_data/california_housing_train.csv')
df = df.iloc[:1598,[3,4,5,6]]

In [4]:
df

total_rooms  total_bedrooms  population  households
0          5612.0          1283.0      1015.0       472.0
1          7650.0          1901.0      1129.0       463.0
2           720.0           174.0       333.0       117.0
3          1501.0           337.0       515.0       226.0
4          1454.0           326.0       624.0       262.0
...           ...             ...         ...         ...
1593       2621.0           542.0      1074.0       471.0
1594       5756.0           807.0      2158.0       758.0
1595       4055.0           536.0      1458.0       478.0
1596       5036.0           817.0      2084.0       833.0
1597       2577.0           521.0       956.0       472.0

[1598 rows x 4 columns]

In [5]:
x = np.array(df['population']).reshape(-1,1)
y = np.array(df['households']).reshape(-1,1)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [7]:
clf = XGBRegressor(random_state = 1)
clf.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=1, ...)

In [8]:
clf.score(X_train,y_train)*100

89.13492836307658

In [9]:
clf.predict(X_train)

array([1497.0997 ,   80.94696,  218.68967, ..., 1093.4102 ,  548.8132 ,
        349.3795 ], dtype=float32)

In [10]:
rd = RandomForestRegressor(random_state = 1)
rd.fit(X_train,y_train)

<ipython-input-10-4163d815651e>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rd.fit(X_train,y_train)


RandomForestRegressor(random_state=1)

In [11]:
rd.score(X_train,y_train)*100

96.39143046283408

In [12]:
rd.predict(X_train)

array([1546.32      ,   75.94      ,  227.31      , ...,  948.26      ,
        571.162     ,  290.66561905])

In [13]:
rgd = GradientBoostingRegressor(random_state = 1)
rgd.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingRegressor(random_state=1)

In [14]:
rgd.score(X_train,y_train)*100

92.1556119915112

In [15]:
ada = AdaBoostRegressor()
ada.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostRegressor()

In [16]:
ada.score(X_train,y_train)*100

86.56258343617014

CatBoost

In [17]:
c = cb.CatBoostRegressor(random_state = 1)
c.fit(X_train,y_train)

Learning rate set to 0.042561
0:	learn: 409.4686309	total: 46.9ms	remaining: 46.9s
1:	learn: 396.6055485	total: 47.8ms	remaining: 23.9s
2:	learn: 384.3879343	total: 48.6ms	remaining: 16.2s
3:	learn: 372.1748859	total: 49.5ms	remaining: 12.3s
4:	learn: 361.0348090	total: 50.3ms	remaining: 10s
5:	learn: 350.2369325	total: 51.2ms	remaining: 8.47s
6:	learn: 339.8895524	total: 51.9ms	remaining: 7.37s
7:	learn: 330.2046695	total: 52.7ms	remaining: 6.53s
8:	learn: 321.2958307	total: 53.5ms	remaining: 5.88s
9:	learn: 312.4157791	total: 54.2ms	remaining: 5.37s
10:	learn: 304.0802036	total: 55ms	remaining: 4.94s
11:	learn: 296.4531545	total: 55.8ms	remaining: 4.59s
12:	learn: 288.6589982	total: 56.5ms	remaining: 4.29s
13:	learn: 281.2443695	total: 57.3ms	remaining: 4.04s
14:	learn: 273.9460921	total: 58.1ms	remaining: 3.82s
15:	learn: 267.0590733	total: 58.9ms	remaining: 3.62s
16:	learn: 260.8114310	total: 59.7ms	remaining: 3.45s
17:	learn: 254.9483674	total: 60.5ms	remaining: 3.3s
18:	learn: 24

In [18]:
c.score(X_train,y_train)*100

88.7232753617381

In [19]:
c.predict(X_train)

array([1116.77863788,   99.42377611,  223.80460614, ..., 1072.93415607,
        551.18377218,  364.27826709])

In [20]:
train_data = lgb.Dataset(X_train, label=y_train)
test_data = lgb.Dataset(X_test, label=y_test)

LIGHT GBM

In [21]:
light = lgb.train({}, train_data, num_boost_round=100, valid_sets=[test_data])

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000419 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 255
[LightGBM] [Info] Number of data points in the train set: 1278, number of used features: 1
[LightGBM] [Info] Start training from score 547.636933


/usr/local/lib/python3.10/dist-packages/lightgbm/basic.py:300: UserWarning: Converting column-vector to 1d array
  _log_warning('Converting column-vector to 1d array')


In [22]:
light.predict(X_train)
light.predict(X_test)

array([1569.06311592,  190.6378567 ,  720.57784897,  492.48492697,
       1662.08072743,  605.61756207,  673.4127022 ,  411.26205017,
        371.66361441,  559.0225676 ,  268.29879655,  223.3576639 ,
        666.48305853,  262.92778286,   26.96157446,  618.02823995,
        488.68050399,  308.09194189,  646.30739684, 1528.55157725,
        425.73989997,  322.02188461,  385.74583254,  305.18845803,
        322.02188461,  488.24639671, 1001.42271237, 1652.78100561,
        780.83341832,  243.35856475,  265.12579878,  425.73989997,
        190.6378567 ,  223.3576639 ,  479.10551756,  943.51314228,
        591.4755381 ,  396.13246925,  459.82301892,  479.10551756,
        553.25925639,   53.56386402,  223.3576639 ,  190.6378567 ,
        177.29872437,  347.65926307,  167.6784691 ,  692.24225066,
        553.25925639,  591.4755381 , 2479.58948976,  411.26205017,
       1237.70792043,  243.35856475,  135.16957434,  658.20392236,
        448.07256289,  488.24639671,  425.73989997,  720.82300